SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS usuarios_cursos_favoritos;
DROP TABLE IF EXISTS cursos_posts;
DROP TABLE IF EXISTS provas_atividades;
DROP TABLE IF EXISTS opcoes;
DROP TABLE IF EXISTS questionarios;
DROP TABLE IF EXISTS atividades;
DROP TABLE IF EXISTS provas;
DROP TABLE IF EXISTS artigos;
DROP TABLE IF EXISTS cursos;
DROP TABLE IF EXISTS comentarios;
DROP TABLE IF EXISTS usuarios_posts_categorias;
DROP TABLE IF EXISTS posts_categorias;
DROP TABLE IF EXISTS categorias_categorias;
DROP TABLE IF EXISTS feeds_categorias;
DROP TABLE IF EXISTS usuarios_posts;
DROP TABLE IF EXISTS usuarios_amigos;
DROP TABLE IF EXISTS feeds;
DROP TABLE IF EXISTS categorias;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS usuarios;
SET FOREIGN_KEY_CHECKS = 1;
