services:
  web:
    build: ./public
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./public
        target: /var/www/html

  api:
    build: ./api
    ports:
      - "8010:80"
    volumes:
      - type: bind
        source: ./api
        target: /var/www/html

  db:
    build: ./api/db
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql

volumes:
  db-data:

#   services:
#   web:
#     build: ./public
#     ports:
#       - "8000:80"
#     volumes:
#       - type: bind
#         source: ./public
#         target: /var/www/html
#   api:
#     build: ./api
#     ports:
#       - "8010:80"
#     volumes:
#       - type: bind
#         source: ./api
#         target: /var/www/html
#   db:
#     build: ./api/db
#     volumes:
#       - type: volume
#         source: db-data
#         target: /var/lib/mysql
# volumes:
#   db-data:
    
